/**
 * Repeatable fixture generator for the mock-portal demonstration.
 *
 * Produces:
 *   - samples/documents/*.pdf  (via pdf-lib — pure JS, no native deps)
 *   - samples/documents/id-proof.png (via a headless Playwright screenshot —
 *     reuses the Playwright dependency already required elsewhere instead of
 *     adding a raster/font-rendering library)
 *   - samples/application.sample.json (valid, fully fillable)
 *   - samples/application.invalid.json (one controlled failure: a missing
 *     required attachment)
 *   - samples/README.md (the fictional scenario explanation)
 *
 * Every generated document visibly carries both required disclaimer lines
 * and contains no real seals, signatures, or scannable identity marks.
 * Run: npx tsx scripts/generate-fixtures.ts
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { chromium } from "playwright";
import { MOCK_DOC_SPECS } from "../src/shared/contracts";
import { decodesPdf, decodesPng } from "../src/shared/file-checks";

const SAMPLES_DIR = path.join(__dirname, "..", "samples");
const DOCS_DIR = path.join(SAMPLES_DIR, "documents");

const DISCLAIMER_1 = "SAMPLE — FOR SOFTWARE TESTING ONLY";
const DISCLAIMER_2 = "NOT A GOVERNMENT-ISSUED DOCUMENT";

const APPLICANT = {
  fullName: "Fictional Demo Applicant",
  fatherName: "Fictional Demo Guardian",
  address: "12, Demo Test Lane, Sample Nagar P.O., Ernakulam"
};

async function makePdf(fileName: string, title: string, bodyLines: string[]): Promise<string> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595.28, 841.89]); // A4 portrait, points
  const font = await doc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await doc.embedFont(StandardFonts.Helvetica);

  let y = 780;
  page.drawText(title, { x: 50, y, size: 16, font, color: rgb(0.05, 0.05, 0.4) });
  y -= 40;

  page.drawRectangle({ x: 40, y: y - 10, width: 515, height: 50, color: rgb(1, 0.95, 0.85), borderColor: rgb(0.8, 0.2, 0.1), borderWidth: 1.5 });
  page.drawText(DISCLAIMER_1, { x: 50, y: y + 20, size: 13, font, color: rgb(0.6, 0.1, 0.1) });
  page.drawText(DISCLAIMER_2, { x: 50, y: y, size: 13, font, color: rgb(0.6, 0.1, 0.1) });
  y -= 70;

  for (const line of bodyLines) {
    page.drawText(line, { x: 50, y, size: 11, font: bodyFont, color: rgb(0.1, 0.1, 0.1) });
    y -= 22;
  }

  y -= 20;
  page.drawText("Generated by scripts/generate-fixtures.ts for local demonstration only.", {
    x: 50, y, size: 9, font: bodyFont, color: rgb(0.4, 0.4, 0.4)
  });

  const bytes = await doc.save();
  const outPath = path.join(DOCS_DIR, fileName);
  fs.writeFileSync(outPath, bytes);
  return outPath;
}

/** Verifies the PDF actually decodes, via the same check src/main/file-validator.ts uses. */
async function verifyPdf(filePath: string): Promise<void> {
  const result = await decodesPdf(fs.readFileSync(filePath));
  if (!result.ok) throw new Error(`${filePath}: ${result.detail}`);
}

async function makeIdProofPng(): Promise<string> {
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>
    body { margin:0; width:640px; height:440px; font-family: Arial, sans-serif; background:#eef3ff; }
    .card { box-sizing:border-box; width:640px; height:440px; padding:24px; border:6px solid #0b3d91; background:linear-gradient(180deg,#ffffff,#eef3ff); }
    .banner { background:#fdecec; border:2px solid #c00000; color:#8f1111; font-weight:bold; padding:8px 12px; text-align:center; font-size:15px; }
    .title { color:#0b3d91; font-weight:bold; font-size:18px; margin-top:16px; }
    .row { margin-top:10px; font-size:13px; color:#243152; }
    .row b { display:inline-block; width:140px; }
    .placeholder-photo { width:90px; height:110px; background:repeating-linear-gradient(45deg,#ccc,#ccc 6px,#eee 6px,#eee 12px); border:2px dashed #888; float:right; text-align:center; font-size:10px; color:#555; display:flex; align-items:center; justify-content:center; overflow:hidden; }
  </style></head><body>
    <div class="card">
      <div class="banner">SAMPLE &mdash; FOR SOFTWARE TESTING ONLY<br/>NOT A GOVERNMENT-ISSUED DOCUMENT</div>
      <div class="placeholder-photo">NO PHOTO<br/>(TEST FIXTURE)</div>
      <div class="title">ID PROOF &mdash; TESTING PLACEHOLDER</div>
      <div class="row"><b>Name:</b> ${APPLICANT.fullName}</div>
      <div class="row"><b>Guardian:</b> ${APPLICANT.fatherName}</div>
      <div class="row"><b>Address:</b> ${APPLICANT.address}</div>
      <div class="row"><b>Test Reference No:</b> TESTID-0000-0000 (synthetic, mock-only)</div>
      <div class="row" style="clear:both;margin-top:20px;color:#888;font-size:11px;">No seal, signature, or scannable identity code is present. This image was generated for local software testing.</div>
    </div>
  </body></html>`;

  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 640, height: 400 } });
    await page.setContent(html, { waitUntil: "load" });
    const outPath = path.join(DOCS_DIR, "id-proof.png");
    await page.locator(".card").screenshot({ path: outPath });
    return outPath;
  } finally {
    await browser.close();
  }
}

/** Verifies the PNG actually decodes, via the same check src/main/file-validator.ts uses. */
function verifyPng(filePath: string): void {
  const result = decodesPng(fs.readFileSync(filePath));
  if (!result.ok) throw new Error(`${filePath}: ${result.detail}`);
}

function sha256Of(filePath: string): string {
  return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

async function main() {
  fs.mkdirSync(DOCS_DIR, { recursive: true });

  const docBodies: Record<string, string[]> = {
    ration: [`Ration Card No: DEMO-RC-000123`, `Head of family: ${APPLICANT.fullName}`, `Card type: Test fixture — priority category not applicable`],
    income: [`Employer: Fictional Test Employer Pvt Ltd (synthetic)`, `Employee: ${APPLICANT.fullName}`, `Declared annual salary: Rs. 1,80,000 (synthetic figure)`],
    landtax: [`Property held by: ${APPLICANT.fullName}`, `Land Tax Receipt No: TEST-LT-000123`, `Amount: Rs. 250 (synthetic)`],
    basictax: [`Property held by: ${APPLICANT.fullName}`, `Basic Tax Receipt No: TEST-BT-000123`, `Amount: Rs. 120 (synthetic)`],
    affidavit: [`Affiant: ${APPLICANT.fullName}`, `Declared purpose: Bank Loan (synthetic scenario)`, `This is a placeholder affidavit body for demonstration only.`]
  };

  const results: Record<string, { path: string; sha256: string; sizeBytes: number }> = {};

  for (const doc of MOCK_DOC_SPECS) {
    if (doc.key === "idproof") continue; // generated as PNG below
    const fileName = `${doc.key === "ration" ? "ration-card" : doc.key === "income" ? "income-proof" : doc.key === "landtax" ? "land-tax-receipt" : doc.key === "basictax" ? "basic-tax-receipt" : "affidavit"}.pdf`;
    const filePath = await makePdf(fileName, doc.label.toUpperCase() + " (SAMPLE)", docBodies[doc.key]);
    await verifyPdf(filePath);
    results[doc.key] = { path: filePath, sha256: sha256Of(filePath), sizeBytes: fs.statSync(filePath).size };
    console.log(`OK  pdf   ${doc.key.padEnd(10)} -> ${path.relative(SAMPLES_DIR, filePath)}`);
  }

  const idProofPath = await makeIdProofPng();
  verifyPng(idProofPath);
  results.idproof = { path: idProofPath, sha256: sha256Of(idProofPath), sizeBytes: fs.statSync(idProofPath).size };
  console.log(`OK  png   idproof    -> ${path.relative(SAMPLES_DIR, idProofPath)}`);

  const fields = {
    fullName: APPLICANT.fullName,
    gender: "Female",
    dob: "1990-05-14",
    fatherName: APPLICANT.fatherName,
    relation: "Self",
    address: APPLICANT.address,
    district: "Ernakulam",
    taluk: "Kanayannur",
    village: "Elamkulam",
    pincode: "682020",
    mobile: "9999999999",
    email: "demo.applicant@example.invalid",
    aadhaar: "999999999999",
    ration: "DEMO-RC-000123",
    purpose: "Bank Loan",
    certLang: "English",
    land: "0",
    salary: "180000",
    business: "0",
    labour: "0",
    nri: "0",
    rent: "0"
  };

  const attachments = MOCK_DOC_SPECS.map((d) => ({
    fieldKey: d.key,
    path: `./documents/${path.basename(results[d.key].path)}`
  }));

  const validSample = { schemaVersion: "1.0", service: "income_certificate", demoOnly: true, fields, attachments };
  fs.writeFileSync(path.join(SAMPLES_DIR, "application.sample.json"), JSON.stringify(validSample, null, 2) + "\n");

  // Controlled failure: the required "landtax" attachment is missing. Everything
  // else stays valid so this one, isolated failure is what validation should catch.
  const invalidAttachments = attachments.filter((a) => a.fieldKey !== "landtax");
  const invalidSample = { schemaVersion: "1.0", service: "income_certificate", demoOnly: true, fields, attachments: invalidAttachments };
  fs.writeFileSync(path.join(SAMPLES_DIR, "application.invalid.json"), JSON.stringify(invalidSample, null, 2) + "\n");

  fs.writeFileSync(
    path.join(SAMPLES_DIR, "README.md"),
    `# Fixture scenario\n\n` +
      `Written for: whoever runs the demonstration (Mohan, or anyone watching it).\n\n` +
      `**Fictional applicant:** "${APPLICANT.fullName}", demo-only person applying for an\n` +
      `Income Certificate from the mock eDistrict Kerala portal for the purpose\n` +
      `"Bank Loan". District Ernakulam. All identifiers (Aadhaar-shaped number, ration\n` +
      `card number, mobile number, tax receipt numbers) are synthetic patterns chosen\n` +
      `to satisfy the portal's own format checks (e.g. Aadhaar must be exactly 12\n` +
      `digits if provided) — none correspond to real people, real documents, or real\n` +
      `government identifiers. The email uses the \`.invalid\` TLD (reserved by RFC\n` +
      `2606 for exactly this purpose — guaranteed non-deliverable and non-real).\n\n` +
      `**application.sample.json** — every required field filled, all 6 documents\n` +
      `attached (5 required + the optional affidavit), should validate cleanly and\n` +
      `run to the Stage 3 review screen without any blocking issue.\n\n` +
      `**application.invalid.json** — identical to the valid sample except the\n` +
      `required "landtax" (Land Tax Receipt) attachment is missing. This is the one\n` +
      `deliberate, isolated failure used to prove the app's pre-flight validation\n` +
      `actually rejects an incomplete case instead of opening the browser anyway.\n\n` +
      `**documents/** — generated by \`scripts/generate-fixtures.ts\`. Five PDFs\n` +
      `(pdf-lib) and one PNG (a Playwright screenshot of a plain HTML placeholder —\n` +
      `no canvas/font-rendering dependency needed). Every file visibly carries both\n` +
      `"SAMPLE — FOR SOFTWARE TESTING ONLY" and "NOT A GOVERNMENT-ISSUED DOCUMENT",\n` +
      `and none contains a real seal, signature, or scannable identity code. Each\n` +
      `file is verified to actually decode right after generation (PDF: reloaded and\n` +
      `page-counted with pdf-lib; PNG: reloaded as a real <img> in headless Chromium\n` +
      `and checked for non-zero natural dimensions).\n\n` +
      `Regenerate at any time with: \`npx tsx scripts/generate-fixtures.ts\`\n`
  );

  console.log("\nWrote samples/application.sample.json, samples/application.invalid.json, samples/README.md");
}

main().catch((err) => {
  console.error("Fixture generation failed:", err);
  process.exit(1);
});
